# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dca97ceec63184d02af68e3d1fdc63175cc24a46cf36641164310a7385e51e7d85c8dca0970a9e9f8a0245d74d3b14b4ac28beb7312582a28f5d13af53217c6f

test:
  secret_key_base: 563f3226c59806f9a410c615ac8f690445aeab441b637970c453e56a7b1224087a757c52bf3c29362faaaecb61390b537e90f6264eab437c3829ad530f80af03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
